package inventorymanagement;


import inventorymanagement.MyConnection;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Supplier extends javax.swing.JFrame implements KeyListener {
    static Statement st;
    static  PreparedStatement pr;
     MyConnection con ;    
    
    public Supplier() throws SQLException {
        try{
            con = new MyConnection();       
                initComponents();
                addKeyListener(this);
                setFocusable(true);
                setFocusTraversalKeysEnabled(false);
                setTitle("Supplier");
                setLocationRelativeTo(null);   
                search_tf.addKeyListener((KeyListener) this);      
        }
        catch(Exception e){
             
         }
    }

    
             /**
              * This method is called from within the constructor to initialize the form.
              * WARNING: Do NOT modify this code. The content of this method is always
              * regenerated by the Form Editor.
              */
          
            
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        dlct_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        search_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        company_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        contctprsn_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phn_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        status_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        address_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_btn.setText("Add");
        add_btn.setToolTipText("Fill all fields and click this to add new supplier");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        edit_btn.setText("Edit");
        edit_btn.setToolTipText("Select any row and click this to make changes to row");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.setToolTipText("Finalize changes and click  this to update it");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        dlct_btn.setText("Delete");
        dlct_btn.setToolTipText("Select any row and click this to delete it");
        dlct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlct_btnActionPerformed(evt);
            }
        });

        view_btn.setText("View");
        view_btn.setToolTipText("Click this to view all  suppliers");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        jLabel6.setText("Search");

        search_tf.setToolTipText("Enter the company name here to check its all suppliers");
        search_tf.setName(""); // NOI18N
        search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tfActionPerformed(evt);
            }
        });

        jLabel7.setText("Company Name");

        company_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_tfActionPerformed(evt);
            }
        });

        jLabel8.setText("Contact_Person");

        jLabel9.setText("Phone");

        jLabel10.setText("Status");

        jLabel11.setText("Address");

        address_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_tfActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Contact_Person", "Phone", "Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(company_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addComponent(address_tf)
                                .addComponent(jLabel10)
                                .addComponent(status_tf))
                            .addComponent(contctprsn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(dlct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dlct_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(company_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contctprsn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void company_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company_tfActionPerformed

    private void search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tfActionPerformed
   
    }//GEN-LAST:event_search_tfActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
 if(!company_tf.equals("") && !contctprsn_tf.equals("") && !phn_tf.equals("") && !address_tf.equals("")
                && !status_tf.equals("")){     try {
           String query = "INSERT INTO Supplier(company,contact_person,phone_no,address,status)"
                + "VALUES('"+company_tf.getText()+"','"+contctprsn_tf.getText()+"','"+Integer.parseInt(phn_tf.getText())+"','"+address_tf.getText()+"','"+status_tf.getText()+"');";
        
                int i = con.st.executeUpdate(query);
                if(i==1){
                    JOptionPane.showMessageDialog(null, "Item Inserted Successfully.");
                    company_tf.setText("");
                    contctprsn_tf.setText("");
                    phn_tf.setText("");
                    address_tf.setText("");
                    status_tf.setText("");
                    
                    updateTable();
                }
                else
                    JOptionPane.showMessageDialog(null, "Unable to add Item!!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Unable to add Item!!");
          
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Fill Complete Information!!");
     
    
    }//GEN-LAST:event_add_btnActionPerformed

    private void address_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_tfActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
 try {
            int num = table.getSelectedRow();
           
            TableModel model = table.getModel();
            Object code = model.getValueAt(num,2);
            con.rs = con.st.executeQuery("Select * from Supplier where phone_no ="+code);
            con.rs.next();
            company_tf.setEditable(true);
            company_tf.setText(model.getValueAt(num,0).toString());
            contctprsn_tf.setEnabled(true);
            contctprsn_tf.setText(model.getValueAt(num,1).toString());
            phn_tf.setEditable(true);
            phn_tf.setText(model.getValueAt(num,2).toString());
            address_tf.setEditable(true);
            address_tf.setText(model.getValueAt(num,3).toString());
            status_tf.setEditable(true);
            status_tf.setText(model.getValueAt(num,4).toString());
            phn_tf.setEditable(false);
            //st.executeUpdate("delete from Supplierlier where phone_no="+code);
            // TODO add your handling code here:
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
               }
                                        
    }//GEN-LAST:event_edit_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
       try {
            String query = "Select * from Supplier";
            con.rs= con.st.executeQuery(query);
            Object col[] = {"company","contact_person","phone","address","status"};
        //    String data[][]={{company_tf.getText(),contctprsn_tf.getText(),phn_tf.getText(),address_tf.getText(),status_tf.getText()}};
            DefaultTableModel model = new DefaultTableModel(col,0);
            model.setRowCount(0);
            int i =0;
            while(con.rs.next()){
                model.addRow( new Object[]{con.rs.getString(1),con.rs.getString(2),con.rs.getInt(3),con.rs.getString(4),con.rs.getString(5)});
                i++;
            }
            table.setModel(model);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
           }
    }//GEN-LAST:event_view_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        try {
        int num = table.getSelectedRow();
            TableModel model = table.getModel();
            Object code = phn_tf.getText();
            
        String value1=company_tf.getText();
        String value2=contctprsn_tf.getText();
        String value3=phn_tf.getText();
        String value4=address_tf.getText();
        String value5=status_tf.getText();
        
        String query="update Supplier set company='"+value1+"', contact_person='"+value2+"', phone_no='"+value3+"', "
                + "address='"+value4+"', status='"+value5+"' where phone_no='"+code+"' ;" ;
                int i=con.st.executeUpdate(query);
                            System.out.println(query);
        if(i==1){
            JOptionPane.showMessageDialog(null, "Update Successfully!!!");
            updateTable();
            company_tf.setText("");
            contctprsn_tf.setText("");
            phn_tf.setText("");
            address_tf.setText("");
            status_tf.setText("");
            phn_tf.setEditable(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
            
        }catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
        }
     
    }//GEN-LAST:event_save_btnActionPerformed

    private void dlct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlct_btnActionPerformed
      try {
            int num = table.getSelectedRow();
            TableModel model = table.getModel();
            //System.out.println(model.getValueAt(num, 1));
            Object code = model.getValueAt(num, 2);
            String query = "delete from Supplier where phone_no ='"+code+"';";
            int i = con.st.executeUpdate(query);
            if(i==1){
                JOptionPane.showMessageDialog(null,"Deleted Successfully.");
                updateTable();
            }
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Unable to delete data!!");
           }
    
    }//GEN-LAST:event_dlct_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
           
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
               //com.jtattoo.plaf.bernstein.BernsteinLookAndFeel
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Supplier().setVisible(true);
                } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
            }
            }
        });
    }
 public  void updateTable() throws SQLException{
     String query = "Select * from Supplier";
     con.rs= con.st.executeQuery(query);
    Object col[] = {"company","contact_person","phone_no","address","status"};   
       DefaultTableModel model = new DefaultTableModel(col,0);
            
   while(con.rs.next()){
       model.addRow( new Object[]{con.rs.getString(1),con.rs.getString(2),con.rs.getInt(3),con.rs.getString(4),con.rs.getString(5)});
                
            }
            table.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_tf;
    private javax.swing.JTextField company_tf;
    private javax.swing.JTextField contctprsn_tf;
    private javax.swing.JButton dlct_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phn_tf;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField search_tf;
    private javax.swing.JTextField status_tf;
    private static javax.swing.JTable table;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
    }
      @Override
    public void keyPressed(KeyEvent ke) {
        try{
         if(KeyEvent.getKeyText(ke.getKeyCode()).equalsIgnoreCase("Escape")){
                this.setVisible(false);
                new Dashboard().setVisible(true);
            }
        if(KeyEvent.getKeyText(ke.getKeyCode()).equals("Enter")&& !search_tf.equals("")){
            try {
                
                
                pr.setString(1, search_tf.getText());
                con.rs = con.st.executeQuery("Select * from Supplier where company=?"+search_tf.getText());
              
                Object col[] = {"company","contact_person","phone_no","address","status"};
                DefaultTableModel model = new DefaultTableModel(col,0);
                    
             while(con.rs.next()){
                model.addRow( new Object[]{con.rs.getString(1),con.rs.getString(2),con.rs.getInt(3),con.rs.getString(4),con.rs.getString(5)});
                          }
             
                      table.setModel(model);            
                      
            }catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
            }
            
        }  
    }catch(Exception e){}            
   }
    @Override
    public void keyReleased(KeyEvent ke) {
    }
}
